config/routes.rb
Rails.application.routes.draw do
  root to: "pets#index"
   resources :pets, only: [:index, :show, :new, :create] do
    resources :appointments, only: [:new, :create]
   end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :pet
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :appointments
  # Through means that an appoinment for this animal exists
  has_many :doctors, through: :appointments

  def calculate
    2 + 2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @pet = Pet.find(params[:pet_id])
    @appointment.pet = @pet
    @appointment.save

    redirect_to pet_path(@pet)


  end


  private

  def appointment_params
    params.require(:appointment).permit(:date, :reason, :doctor_id)
    # params[:appointment][:reason]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<%= simple_form_for [@pet, @appointment] do |f| %>
  <%= f.input :date %>
  <%= f.input :reason %>
  <%= f.association :doctor, collection: Doctor.where(available: true) %>


  <%= f.submit "Create Appointment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VETCLINIC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <h1>Navbar</h1>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pets/index.html.erb
<h1>My Pets</h1>

<ul>
  <% @pets.each do |pet| %>
   <li><%= link_to pet.name, pet_path(pet.id) %></li>
  <% end %>
</ul>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2><%= @pet.species.capitalize %></h2>
<h3><%= @pet.age %></h3>

<%= link_to "Make Appointment for #{@pet.name}", new_pet_appointment_path(@pet.id) %>

<h2>Appoinment</h2>

<ul>
  <% @pet.appointments.each do |appointment| %>
    <li>
    <%= appointment.reason %>
    <%= appointment.doctor.name %>
     <%= appointment.date %>
    </li>
  <% end %>
</ul>